<?php

/**
 * Common filter form base class.
 *
 * @package    siwapp
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfDoctrineFormFilterGeneratedTemplate.php 29570 2010-05-21 14:49:47Z Kris.Wallsmith $
 */
abstract class BaseCommonFormFilter extends BaseFormFilterDoctrine
{
  public function setup()
  {
    $this->setWidgets(array(
      'company_id'              => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Company'), 'add_empty' => true)),
      'series_id'               => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Series'), 'add_empty' => true)),
      'customer_id'             => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Customer'), 'add_empty' => true)),
      'customer_name'           => new sfWidgetFormFilterInput(),
      'customer_identification' => new sfWidgetFormFilterInput(),
      'customer_email'          => new sfWidgetFormFilterInput(),
      'customer_phone'          => new sfWidgetFormFilterInput(),
      'customer_fax'            => new sfWidgetFormFilterInput(),
      'supplier_id'             => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('Supplier'), 'add_empty' => true)),
      'supplier_name'           => new sfWidgetFormFilterInput(),
      'supplier_identification' => new sfWidgetFormFilterInput(),
      'supplier_email'          => new sfWidgetFormFilterInput(),
      'supplier_phone'          => new sfWidgetFormFilterInput(),
      'supplier_fax'            => new sfWidgetFormFilterInput(),
      'invoicing_address'       => new sfWidgetFormFilterInput(),
      'invoicing_postalcode'    => new sfWidgetFormFilterInput(),
      'invoicing_city'          => new sfWidgetFormFilterInput(),
      'invoicing_state'         => new sfWidgetFormFilterInput(),
      'invoicing_country'       => new sfWidgetFormFilterInput(),
      'shipping_address'        => new sfWidgetFormFilterInput(),
      'shipping_postalcode'     => new sfWidgetFormFilterInput(),
      'shipping_city'           => new sfWidgetFormFilterInput(),
      'shipping_state'          => new sfWidgetFormFilterInput(),
      'shipping_country'        => new sfWidgetFormFilterInput(),
      'contact_person'          => new sfWidgetFormFilterInput(),
      'terms'                   => new sfWidgetFormFilterInput(),
      'notes'                   => new sfWidgetFormFilterInput(),
      'base_amount'             => new sfWidgetFormFilterInput(),
      'discount_amount'         => new sfWidgetFormFilterInput(),
      'net_amount'              => new sfWidgetFormFilterInput(),
      'gross_amount'            => new sfWidgetFormFilterInput(),
      'paid_amount'             => new sfWidgetFormFilterInput(),
      'tax_amount'              => new sfWidgetFormFilterInput(),
      'status'                  => new sfWidgetFormFilterInput(),
      'payment_type_id'         => new sfWidgetFormDoctrineChoice(array('model' => $this->getRelatedModelName('PaymentType'), 'add_empty' => true)),
      'discount'                => new sfWidgetFormFilterInput(array('with_empty' => false)),
      'type'                    => new sfWidgetFormFilterInput(),
      'draft'                   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'closed'                  => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'sent_by_email'           => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'remesed'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'number'                  => new sfWidgetFormFilterInput(),
      'recurring_invoice_id'    => new sfWidgetFormFilterInput(),
      'estimate_id'             => new sfWidgetFormFilterInput(),
      'issue_date'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'due_date'                => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'supplier_reference'      => new sfWidgetFormFilterInput(),
      'days_to_due'             => new sfWidgetFormFilterInput(),
      'enabled'                 => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'max_occurrences'         => new sfWidgetFormFilterInput(),
      'must_occurrences'        => new sfWidgetFormFilterInput(),
      'period'                  => new sfWidgetFormFilterInput(),
      'period_type'             => new sfWidgetFormFilterInput(),
      'starting_date'           => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'finishing_date'          => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'last_execution_date'     => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'created_at'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'updated_at'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
    ));

    $this->setValidators(array(
      'company_id'              => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Company'), 'column' => 'id')),
      'series_id'               => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Series'), 'column' => 'id')),
      'customer_id'             => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Customer'), 'column' => 'id')),
      'customer_name'           => new sfValidatorPass(array('required' => false)),
      'customer_identification' => new sfValidatorPass(array('required' => false)),
      'customer_email'          => new sfValidatorPass(array('required' => false)),
      'customer_phone'          => new sfValidatorPass(array('required' => false)),
      'customer_fax'            => new sfValidatorPass(array('required' => false)),
      'supplier_id'             => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('Supplier'), 'column' => 'id')),
      'supplier_name'           => new sfValidatorPass(array('required' => false)),
      'supplier_identification' => new sfValidatorPass(array('required' => false)),
      'supplier_email'          => new sfValidatorPass(array('required' => false)),
      'supplier_phone'          => new sfValidatorPass(array('required' => false)),
      'supplier_fax'            => new sfValidatorPass(array('required' => false)),
      'invoicing_address'       => new sfValidatorPass(array('required' => false)),
      'invoicing_postalcode'    => new sfValidatorPass(array('required' => false)),
      'invoicing_city'          => new sfValidatorPass(array('required' => false)),
      'invoicing_state'         => new sfValidatorPass(array('required' => false)),
      'invoicing_country'       => new sfValidatorPass(array('required' => false)),
      'shipping_address'        => new sfValidatorPass(array('required' => false)),
      'shipping_postalcode'     => new sfValidatorPass(array('required' => false)),
      'shipping_city'           => new sfValidatorPass(array('required' => false)),
      'shipping_state'          => new sfValidatorPass(array('required' => false)),
      'shipping_country'        => new sfValidatorPass(array('required' => false)),
      'contact_person'          => new sfValidatorPass(array('required' => false)),
      'terms'                   => new sfValidatorPass(array('required' => false)),
      'notes'                   => new sfValidatorPass(array('required' => false)),
      'base_amount'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'discount_amount'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'net_amount'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'gross_amount'            => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'paid_amount'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tax_amount'              => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'status'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'payment_type_id'         => new sfValidatorDoctrineChoice(array('required' => false, 'model' => $this->getRelatedModelName('PaymentType'), 'column' => 'id')),
      'discount'                => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'type'                    => new sfValidatorPass(array('required' => false)),
      'draft'                   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'closed'                  => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'sent_by_email'           => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'remesed'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'number'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'recurring_invoice_id'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'estimate_id'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'issue_date'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'due_date'                => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'supplier_reference'      => new sfValidatorPass(array('required' => false)),
      'days_to_due'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'enabled'                 => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'max_occurrences'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'must_occurrences'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'period'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'period_type'             => new sfValidatorPass(array('required' => false)),
      'starting_date'           => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'finishing_date'          => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'last_execution_date'     => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDateTime(array('required' => false)))),
      'created_at'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
      'updated_at'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 00:00:00')), 'to_date' => new sfValidatorDateTime(array('required' => false, 'datetime_output' => 'Y-m-d 23:59:59')))),
    ));

    $this->widgetSchema->setNameFormat('common_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    $this->setupInheritance();

    parent::setup();
  }

  public function getModelName()
  {
    return 'Common';
  }

  public function getFields()
  {
    return array(
      'id'                      => 'Number',
      'company_id'              => 'ForeignKey',
      'series_id'               => 'ForeignKey',
      'customer_id'             => 'ForeignKey',
      'customer_name'           => 'Text',
      'customer_identification' => 'Text',
      'customer_email'          => 'Text',
      'customer_phone'          => 'Text',
      'customer_fax'            => 'Text',
      'supplier_id'             => 'ForeignKey',
      'supplier_name'           => 'Text',
      'supplier_identification' => 'Text',
      'supplier_email'          => 'Text',
      'supplier_phone'          => 'Text',
      'supplier_fax'            => 'Text',
      'invoicing_address'       => 'Text',
      'invoicing_postalcode'    => 'Text',
      'invoicing_city'          => 'Text',
      'invoicing_state'         => 'Text',
      'invoicing_country'       => 'Text',
      'shipping_address'        => 'Text',
      'shipping_postalcode'     => 'Text',
      'shipping_city'           => 'Text',
      'shipping_state'          => 'Text',
      'shipping_country'        => 'Text',
      'contact_person'          => 'Text',
      'terms'                   => 'Text',
      'notes'                   => 'Text',
      'base_amount'             => 'Number',
      'discount_amount'         => 'Number',
      'net_amount'              => 'Number',
      'gross_amount'            => 'Number',
      'paid_amount'             => 'Number',
      'tax_amount'              => 'Number',
      'status'                  => 'Number',
      'payment_type_id'         => 'ForeignKey',
      'discount'                => 'Number',
      'type'                    => 'Text',
      'draft'                   => 'Boolean',
      'closed'                  => 'Boolean',
      'sent_by_email'           => 'Boolean',
      'remesed'                 => 'Boolean',
      'number'                  => 'Number',
      'recurring_invoice_id'    => 'Number',
      'estimate_id'             => 'Number',
      'issue_date'              => 'Date',
      'due_date'                => 'Date',
      'supplier_reference'      => 'Text',
      'days_to_due'             => 'Number',
      'enabled'                 => 'Boolean',
      'max_occurrences'         => 'Number',
      'must_occurrences'        => 'Number',
      'period'                  => 'Number',
      'period_type'             => 'Text',
      'starting_date'           => 'Date',
      'finishing_date'          => 'Date',
      'last_execution_date'     => 'Date',
      'created_at'              => 'Date',
      'updated_at'              => 'Date',
    );
  }
}
