<?php

/**
 * BaseInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property RecurringInvoice $RecurringInvoice
 * @property Estimate $Estimate
 * 
 * @method RecurringInvoice getRecurringInvoice() Returns the current record's "RecurringInvoice" value
 * @method Estimate         getEstimate()         Returns the current record's "Estimate" value
 * @method Invoice          setRecurringInvoice() Sets the current record's "RecurringInvoice" value
 * @method Invoice          setEstimate()         Sets the current record's "Estimate" value
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInvoice extends Common
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RecurringInvoice', array(
             'local' => 'recurring_invoice_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Estimate', array(
             'local' => 'estimate_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}