<?php

/**
 * BaseExpenseType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property string $name
 * @property boolean $enabled
 * @property Company $Company
 * @property Doctrine_Collection $Supplier
 * @property Doctrine_Collection $Items
 * 
 * @method integer             getCompanyId()  Returns the current record's "company_id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method boolean             getEnabled()    Returns the current record's "enabled" value
 * @method Company             getCompany()    Returns the current record's "Company" value
 * @method Doctrine_Collection getSupplier()   Returns the current record's "Supplier" collection
 * @method Doctrine_Collection getItems()      Returns the current record's "Items" collection
 * @method ExpenseType         setCompanyId()  Sets the current record's "company_id" value
 * @method ExpenseType         setName()       Sets the current record's "name" value
 * @method ExpenseType         setEnabled()    Sets the current record's "enabled" value
 * @method ExpenseType         setCompany()    Sets the current record's "Company" value
 * @method ExpenseType         setSupplier()   Sets the current record's "Supplier" collection
 * @method ExpenseType         setItems()      Sets the current record's "Items" collection
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpenseType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expense_type');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Supplier', array(
             'local' => 'id',
             'foreign' => 'expense_type_id'));

        $this->hasMany('Item as Items', array(
             'local' => 'id',
             'foreign' => 'expense_type_id'));
    }
}