<?php

/**
 * BaseProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property string $name
 * @property Company $Company
 * @property Doctrine_Collection $ProductCategory
 * 
 * @method integer             getCompanyId()       Returns the current record's "company_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Company             getCompany()         Returns the current record's "Company" value
 * @method Doctrine_Collection getProductCategory() Returns the current record's "ProductCategory" collection
 * @method ProductCategory     setCompanyId()       Sets the current record's "company_id" value
 * @method ProductCategory     setName()            Sets the current record's "name" value
 * @method ProductCategory     setCompany()         Sets the current record's "Company" value
 * @method ProductCategory     setProductCategory() Sets the current record's "ProductCategory" collection
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_category');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Product as ProductCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}