<?php

/**
 * BaseTaxCondition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property string $name
 * @property clob $description
 * @property boolean $enabled
 * @property Company $Company
 * @property Doctrine_Collection $TaxCondition
 * 
 * @method integer             getCompanyId()    Returns the current record's "company_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method clob                getDescription()  Returns the current record's "description" value
 * @method boolean             getEnabled()      Returns the current record's "enabled" value
 * @method Company             getCompany()      Returns the current record's "Company" value
 * @method Doctrine_Collection getTaxCondition() Returns the current record's "TaxCondition" collection
 * @method TaxCondition        setCompanyId()    Sets the current record's "company_id" value
 * @method TaxCondition        setName()         Sets the current record's "name" value
 * @method TaxCondition        setDescription()  Sets the current record's "description" value
 * @method TaxCondition        setEnabled()      Sets the current record's "enabled" value
 * @method TaxCondition        setCompany()      Sets the current record's "Company" value
 * @method TaxCondition        setTaxCondition() Sets the current record's "TaxCondition" collection
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTaxCondition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tax_condition');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Customer as TaxCondition', array(
             'local' => 'id',
             'foreign' => 'tax_condition_id'));
    }
}