<?php

/**
 * BaseExpense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property RecurringInvoice $RecurringInvoice
 * 
 * @method RecurringInvoice getRecurringInvoice() Returns the current record's "RecurringInvoice" value
 * @method Expense          setRecurringInvoice() Sets the current record's "RecurringInvoice" value
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExpense extends Common
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RecurringInvoice', array(
             'local' => 'recurring_invoice_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}