<?php

/**
 * BaseCompanyUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $sf_guard_user_id
 * @property Company $Company
 * @property sfGuardUser $User
 * 
 * @method integer     getCompanyId()        Returns the current record's "company_id" value
 * @method integer     getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method Company     getCompany()          Returns the current record's "Company" value
 * @method sfGuardUser getUser()             Returns the current record's "User" value
 * @method CompanyUser setCompanyId()        Sets the current record's "company_id" value
 * @method CompanyUser setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method CompanyUser setCompany()          Sets the current record's "Company" value
 * @method CompanyUser setUser()             Sets the current record's "User" value
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompanyUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company_user');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}