<?php

/**
 * BaseCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property string $name
 * @property string $name_slug
 * @property string $identification
 * @property string $email
 * @property string $contact_person
 * @property clob $invoicing_address
 * @property clob $shipping_address
 * @property string $website
 * @property string $phone
 * @property string $mobile
 * @property string $fax
 * @property clob $comments
 * @property Company $Company
 * @property Doctrine_Collection $Commons
 * 
 * @method integer             getCompanyId()         Returns the current record's "company_id" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getNameSlug()          Returns the current record's "name_slug" value
 * @method string              getIdentification()    Returns the current record's "identification" value
 * @method string              getEmail()             Returns the current record's "email" value
 * @method string              getContactPerson()     Returns the current record's "contact_person" value
 * @method clob                getInvoicingAddress()  Returns the current record's "invoicing_address" value
 * @method clob                getShippingAddress()   Returns the current record's "shipping_address" value
 * @method string              getWebsite()           Returns the current record's "website" value
 * @method string              getPhone()             Returns the current record's "phone" value
 * @method string              getMobile()            Returns the current record's "mobile" value
 * @method string              getFax()               Returns the current record's "fax" value
 * @method clob                getComments()          Returns the current record's "comments" value
 * @method Company             getCompany()           Returns the current record's "Company" value
 * @method Doctrine_Collection getCommons()           Returns the current record's "Commons" collection
 * @method Customer            setCompanyId()         Sets the current record's "company_id" value
 * @method Customer            setName()              Sets the current record's "name" value
 * @method Customer            setNameSlug()          Sets the current record's "name_slug" value
 * @method Customer            setIdentification()    Sets the current record's "identification" value
 * @method Customer            setEmail()             Sets the current record's "email" value
 * @method Customer            setContactPerson()     Sets the current record's "contact_person" value
 * @method Customer            setInvoicingAddress()  Sets the current record's "invoicing_address" value
 * @method Customer            setShippingAddress()   Sets the current record's "shipping_address" value
 * @method Customer            setWebsite()           Sets the current record's "website" value
 * @method Customer            setPhone()             Sets the current record's "phone" value
 * @method Customer            setMobile()            Sets the current record's "mobile" value
 * @method Customer            setFax()               Sets the current record's "fax" value
 * @method Customer            setComments()          Sets the current record's "comments" value
 * @method Customer            setCompany()           Sets the current record's "Company" value
 * @method Customer            setCommons()           Sets the current record's "Commons" collection
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('name_slug', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('identification', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('contact_person', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('invoicing_address', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('shipping_address', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('mobile', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('fax', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('comments', 'clob', null, array(
             'type' => 'clob',
             ));


        $this->index('cstm', array(
             'fields' => 
             array(
              0 => 'company_id',
              1 => 'name',
             ),
             ));
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Common as Commons', array(
             'local' => 'id',
             'foreign' => 'customer_id'));
    }
}