<?php

/**
 * Company
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Company extends BaseCompany
{
  public function getDefaultCompany($userid)
  {
    $company = $this->getTable()->createQuery('c')
                 ->where('exists (select company_id from company_user cu where c.id = cu.company_id and cu.sf_guard_user_id = ?) ', $userid)
                 ->fetchOne();
    return $company;
  }
  
  public function loadById($company_id)
  {
      $company = $this->getTable()->createQuery('c')
                 ->where('c.id = ?',$company_id)
                 ->fetchOne();
    return $company;

  
  }

  public function getLogoURL()
  {
    if(!$this->getLogo())
        return false;
    return str_replace("\\", "/",self::getUploadsDir().'/'.$this->getLogo());
  }

  public static function getUploadsDir()
  {
    $uri = sfContext::getInstance()->getRequest()->getUri();
    $server_url = substr($uri,0,strpos($uri,'/',9));
    $root_path = substr($_SERVER['SCRIPT_NAME'],0,strrpos($_SERVER['SCRIPT_NAME'],'/'));
    $web_dir = str_replace(DIRECTORY_SEPARATOR,'/',sfConfig::get('sf_web_dir'));
    $upload_dir = str_replace(DIRECTORY_SEPARATOR,'/',sfConfig::get('sf_upload_dir'));
    return $server_url.$root_path.str_replace($web_dir, null, $upload_dir);
  }
}
