<?php

/**
 * CompanyUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyUser');
    }
}