<?php

/**
 * ExpenseTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpenseTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpenseTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExpenseType');
    }

    public function getCurrentCompany()
    {
        $query = $this->createQuery('q')
                ->where('q.company_id = ?', sfContext::getInstance()->getUser()->getAttribute('company_id'))
                ->orderBy('name ASC');
        $result = $query->execute();
        return $result;
    }
    
  /**
   * Returns an associative array with all expense types or those enabled only
   * depending on the param value.
   *
   * @param boolean Return only enabled expense types (default=true)
   * @return array
   * @author Pablo Fiumidinisi <plfiumi@gmail.com>
   **/
  public static function getChoicesForSelect($enabled_only = true)
  {
    $expenseTypes = array();
    $finder = Doctrine_Core::getTable('ExpenseType')->createQuery();
    
    if ($enabled_only)
    {
      $finder->where('Enabled = ?', '1');
    }
    
    $finder->where('company_id = ?', sfContext::getInstance()->getUser()->getAttribute('company_id'));
    
    foreach ($finder->execute() as $s)
    {
      $expenseTypes[$s->id] = $s->name;
    }
    
    return $expenseTypes;
  }
    
}
