<?php

/**
 * ExpenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpenseTable extends CommonTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expense');
    }
    /**
   * Returns the next number for the series
   *
   * @return integer
   * @author Enrique
   **/
  public function getNextNumber($series_id)
  {
    $found = $this->createQuery()
      ->where('Draft = ?', 0)
      ->execute()
      ->count();
    
    if ($found > 0)
    {
      $rs = $this->createQuery()
        ->select('MAX(number) AS max_number')
        ->where('Draft = ?', 0)
        ->fetchOne();
      
      return intval($rs->getMaxNumber()) + 1;
    }
    else
    {
      return 1;
    }
  }
}
