<?php

/**
 * PaymentTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaymentTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaymentTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaymentType');
    }
}