<?php

/**
 * TaxConditionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxConditionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxConditionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxCondition');
    }
    
  /**
   * Returns an associative array with all tax conditions or those enabled only
   * depending on the param value.
   *
   * @param boolean Return only enabled tax conditions (default=true)
   * @return array
   * @author Pablo Fiumidinisi <plfiumi@gmail.com>
   **/
  public static function getChoicesForSelect($enabled_only = true)
  {
    $taxConditions = array();
    $finder = Doctrine_Core::getTable('TaxCondition')->createQuery();
    
    if ($enabled_only)
    {
      $finder->addWhere('enabled = ?', '1');
    }
    
    $finder->addWhere('company_id = ?', sfContext::getInstance()->getUser()->getAttribute('company_id'));
    
    foreach ($finder->execute() as $s)
    {
      $taxConditions[$s->id] = $s->name;
    }

    return $taxConditions;
  }
}