<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeIndex('customer', 'cstm_slug', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
        $this->removeIndex('template', 'template_sluggable', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             'type' => 'unique',
             ));
        $this->createForeignKey('common', 'common_company_id_company_id', array(
             'name' => 'common_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('common', 'common_supplier_id_supplier_id', array(
             'name' => 'common_supplier_id_supplier_id',
             'local' => 'supplier_id',
             'foreign' => 'id',
             'foreignTable' => 'supplier',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('common', 'common_payment_type_id_payment_type_id', array(
             'name' => 'common_payment_type_id_payment_type_id',
             'local' => 'payment_type_id',
             'foreign' => 'id',
             'foreignTable' => 'payment_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('common', 'common_customer_id_customer_id', array(
             'name' => 'common_customer_id_customer_id',
             'local' => 'customer_id',
             'foreign' => 'id',
             'foreignTable' => 'customer',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('common', 'common_series_id_series_id', array(
             'name' => 'common_series_id_series_id',
             'local' => 'series_id',
             'foreign' => 'id',
             'foreignTable' => 'series',
             'onUpdate' => '',
             'onDelete' => 'set null',
             ));
        $this->createForeignKey('common', 'common_recurring_invoice_id_common_id', array(
             'name' => 'common_recurring_invoice_id_common_id',
             'local' => 'recurring_invoice_id',
             'foreign' => 'id',
             'foreignTable' => 'common',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('common', 'common_estimate_id_common_id', array(
             'name' => 'common_estimate_id_common_id',
             'local' => 'estimate_id',
             'foreign' => 'id',
             'foreignTable' => 'common',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('company_user', 'company_user_company_id_company_id', array(
             'name' => 'company_user_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('company_user', 'company_user_sf_guard_user_id_sf_guard_user_id', array(
             'name' => 'company_user_sf_guard_user_id_sf_guard_user_id',
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'cascade',
             ));
        $this->createForeignKey('customer', 'customer_company_id_company_id', array(
             'name' => 'customer_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('expense_type', 'expense_type_company_id_company_id', array(
             'name' => 'expense_type_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('item', 'item_company_id_company_id', array(
             'name' => 'item_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('item', 'item_expense_type_id_expense_type_id', array(
             'name' => 'item_expense_type_id_expense_type_id',
             'local' => 'expense_type_id',
             'foreign' => 'id',
             'foreignTable' => 'expense_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('item_tax', 'item_tax_company_id_company_id', array(
             'name' => 'item_tax_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('payment', 'payment_payment_type_id_payment_type_id', array(
             'name' => 'payment_payment_type_id_payment_type_id',
             'local' => 'payment_type_id',
             'foreign' => 'id',
             'foreignTable' => 'payment_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('payment', 'payment_company_id_company_id', array(
             'name' => 'payment_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('payment_type', 'payment_type_company_id_company_id', array(
             'name' => 'payment_type_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product', 'product_company_id_company_id', array(
             'name' => 'product_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('product', 'product_category_id_product_category_id', array(
             'name' => 'product_category_id_product_category_id',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'product_category',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('product_category', 'product_category_company_id_company_id', array(
             'name' => 'product_category_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('property', 'property_company_id_company_id', array(
             'name' => 'property_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('series', 'series_company_id_company_id', array(
             'name' => 'series_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('supplier', 'supplier_company_id_company_id', array(
             'name' => 'supplier_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('supplier', 'supplier_expense_type_id_expense_type_id', array(
             'name' => 'supplier_expense_type_id_expense_type_id',
             'local' => 'expense_type_id',
             'foreign' => 'id',
             'foreignTable' => 'expense_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('tax', 'tax_company_id_company_id', array(
             'name' => 'tax_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->createForeignKey('template', 'template_company_id_company_id', array(
             'name' => 'template_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('common', 'common_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('common', 'common_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->addIndex('common', 'common_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
        $this->addIndex('common', 'common_customer_id', array(
             'fields' => 
             array(
              0 => 'customer_id',
             ),
             ));
        $this->addIndex('common', 'common_series_id', array(
             'fields' => 
             array(
              0 => 'series_id',
             ),
             ));
        $this->addIndex('common', 'common_recurring_invoice_id', array(
             'fields' => 
             array(
              0 => 'recurring_invoice_id',
             ),
             ));
        $this->addIndex('common', 'common_estimate_id', array(
             'fields' => 
             array(
              0 => 'estimate_id',
             ),
             ));
        $this->addIndex('company_user', 'company_user_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('company_user', 'company_user_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
        $this->addIndex('customer', 'customer_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('expense_type', 'expense_type_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('item', 'item_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('item', 'item_expense_type_id', array(
             'fields' => 
             array(
              0 => 'expense_type_id',
             ),
             ));
        $this->addIndex('item_tax', 'item_tax_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('payment', 'payment_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
        $this->addIndex('payment', 'payment_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('payment_type', 'payment_type_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('product', 'product_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('product', 'product_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('product_category', 'product_category_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('property', 'property_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('series', 'series_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('supplier', 'supplier_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('supplier', 'supplier_expense_type_id', array(
             'fields' => 
             array(
              0 => 'expense_type_id',
             ),
             ));
        $this->addIndex('tax', 'tax_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->addIndex('template', 'template_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
    }

    public function down()
    {
        $this->addIndex('customer', 'cstm_slug', array(
             'fields' => 
             array(
              0 => 'name_slug',
             ),
             'type' => 'unique',
             ));
        $this->addIndex('template', 'template_sluggable', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             'type' => 'unique',
             ));
        $this->dropForeignKey('common', 'common_company_id_company_id');
        $this->dropForeignKey('common', 'common_supplier_id_supplier_id');
        $this->dropForeignKey('common', 'common_payment_type_id_payment_type_id');
        $this->dropForeignKey('common', 'common_customer_id_customer_id');
        $this->dropForeignKey('common', 'common_series_id_series_id');
        $this->dropForeignKey('common', 'common_recurring_invoice_id_common_id');
        $this->dropForeignKey('common', 'common_estimate_id_common_id');
        $this->dropForeignKey('company_user', 'company_user_company_id_company_id');
        $this->dropForeignKey('company_user', 'company_user_sf_guard_user_id_sf_guard_user_id');
        $this->dropForeignKey('customer', 'customer_company_id_company_id');
        $this->dropForeignKey('expense_type', 'expense_type_company_id_company_id');
        $this->dropForeignKey('item', 'item_company_id_company_id');
        $this->dropForeignKey('item', 'item_expense_type_id_expense_type_id');
        $this->dropForeignKey('item_tax', 'item_tax_company_id_company_id');
        $this->dropForeignKey('payment', 'payment_payment_type_id_payment_type_id');
        $this->dropForeignKey('payment', 'payment_company_id_company_id');
        $this->dropForeignKey('payment_type', 'payment_type_company_id_company_id');
        $this->dropForeignKey('product', 'product_company_id_company_id');
        $this->dropForeignKey('product', 'product_category_id_product_category_id');
        $this->dropForeignKey('product_category', 'product_category_company_id_company_id');
        $this->dropForeignKey('property', 'property_company_id_company_id');
        $this->dropForeignKey('series', 'series_company_id_company_id');
        $this->dropForeignKey('supplier', 'supplier_company_id_company_id');
        $this->dropForeignKey('supplier', 'supplier_expense_type_id_expense_type_id');
        $this->dropForeignKey('tax', 'tax_company_id_company_id');
        $this->dropForeignKey('template', 'template_company_id_company_id');
        $this->removeIndex('common', 'common_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('common', 'common_supplier_id', array(
             'fields' => 
             array(
              0 => 'supplier_id',
             ),
             ));
        $this->removeIndex('common', 'common_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
        $this->removeIndex('common', 'common_customer_id', array(
             'fields' => 
             array(
              0 => 'customer_id',
             ),
             ));
        $this->removeIndex('common', 'common_series_id', array(
             'fields' => 
             array(
              0 => 'series_id',
             ),
             ));
        $this->removeIndex('common', 'common_recurring_invoice_id', array(
             'fields' => 
             array(
              0 => 'recurring_invoice_id',
             ),
             ));
        $this->removeIndex('common', 'common_estimate_id', array(
             'fields' => 
             array(
              0 => 'estimate_id',
             ),
             ));
        $this->removeIndex('company_user', 'company_user_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('company_user', 'company_user_sf_guard_user_id', array(
             'fields' => 
             array(
              0 => 'sf_guard_user_id',
             ),
             ));
        $this->removeIndex('customer', 'customer_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('expense_type', 'expense_type_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('item', 'item_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('item', 'item_expense_type_id', array(
             'fields' => 
             array(
              0 => 'expense_type_id',
             ),
             ));
        $this->removeIndex('item_tax', 'item_tax_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('payment', 'payment_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
        $this->removeIndex('payment', 'payment_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('payment_type', 'payment_type_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('product', 'product_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('product', 'product_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('product_category', 'product_category_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('property', 'property_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('series', 'series_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('supplier', 'supplier_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('supplier', 'supplier_expense_type_id', array(
             'fields' => 
             array(
              0 => 'expense_type_id',
             ),
             ));
        $this->removeIndex('tax', 'tax_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
        $this->removeIndex('template', 'template_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
    }
}