<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version7 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common', 'invoicing_postalcode', 'string', '255', array( ));
        $this->addColumn('common', 'invoicing_city', 'string', '255', array( ));
        $this->addColumn('common', 'invoicing_state', 'string', '255', array( ));
        $this->addColumn('common', 'invoicing_country', 'string', '255', array( ));
        $this->addColumn('common', 'shipping_postalcode', 'string', '255', array( ));
        $this->addColumn('common', 'shipping_city', 'string', '255', array( ));
        $this->addColumn('common', 'shipping_state', 'string', '255', array( ));
        $this->addColumn('common', 'shipping_country', 'string', '255', array( ));
        $this->addColumn('customer', 'invoicing_postalcode', 'string', '255', array( ));
        $this->addColumn('customer', 'invoicing_city', 'string', '255', array( ));
        $this->addColumn('customer', 'invoicing_state', 'string', '255', array( ));
        $this->addColumn('customer', 'invoicing_country', 'string', '255', array( ));
        $this->addColumn('customer', 'shipping_postalcode', 'string', '255', array( ));
        $this->addColumn('customer', 'shipping_city', 'string', '255', array( ));
        $this->addColumn('customer', 'shipping_state', 'string', '255', array( ));
        $this->addColumn('customer', 'shipping_country', 'string', '255', array( ));
        $this->addColumn('supplier', 'invoicing_postalcode', 'string', '255', array( ));
        $this->addColumn('supplier', 'invoicing_city', 'string', '255', array( ));
        $this->addColumn('supplier', 'invoicing_state', 'string', '255', array( ));
        $this->addColumn('supplier', 'invoicing_country', 'string', '255', array( ));
        $this->addColumn('company', 'postalcode', 'string', '255', array( ));
        $this->addColumn('company', 'city', 'string', '255', array( ));
        $this->addColumn('company', 'state', 'string', '255', array( ));
        $this->addColumn('company', 'country', 'string', '255', array( ));
       
    }

    public function down()
    {
        $this->removeColumn('common', 'invoicing_postalcode');
        $this->removeColumn('common', 'invoicing_city');
        $this->removeColumn('common', 'invoicing_state');
        $this->removeColumn('common', 'invoicing_country');
        $this->removeColumn('common', 'shipping_postalcode');
        $this->removeColumn('common', 'shipping_city');
        $this->removeColumn('common', 'shipping_state');
        $this->removeColumn('common', 'shipping_country');
        $this->removeColumn('customer', 'invoicing_postalcode');
        $this->removeColumn('customer', 'invoicing_city');
        $this->removeColumn('customer', 'invoicing_state');
        $this->removeColumn('customer', 'invoicing_country');
        $this->removeColumn('customer', 'shipping_postalcode');
        $this->removeColumn('customer', 'shipping_city');
        $this->removeColumn('customer', 'shipping_state');
        $this->removeColumn('customer', 'shipping_country');
        $this->removeColumn('supplier', 'invoicing_postalcode');
        $this->removeColumn('supplier', 'invoicing_city');
        $this->removeColumn('supplier', 'invoicing_state');
        $this->removeColumn('supplier', 'invoicing_country');
        $this->removeColumn('company', 'postalcode');
        $this->removeColumn('company', 'city');
        $this->removeColumn('company', 'state');
        $this->removeColumn('company', 'country');
    }
}
