<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('tax', 'apply_total', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('customer', 'payment_type_id', 'integer');
        $this->addIndex('customer', 'customer_payment_type_idx', array(
             'fields' =>
             array(
              0 => 'payment_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->removeColumn('tax', 'apply_total');
        $this->removeColumn('customer', 'payment_type_id');
        $this->removeIndex('customer', 'customer_payment_type_idx', array(
             'fields' =>
             array(
              0 => 'payment_type_id',
             ),
             ));
    }
}
