<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common', 'buy_order_number', 'string', '10', array(
             ));
        $this->addColumn('common', 'delivery_note_number', 'string', '10', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common', 'buy_order_number');
        $this->removeColumn('common', 'delivery_note_number');
    }
}