<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common', 'shipping_company_data', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common', 'shipping_company_data');
    }
}