<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('company', 'legal_terms');
        $this->addColumn('company', 'invoice_legal_terms', 'clob', '', array(
             ));
        $this->addColumn('company', 'estimate_legal_terms', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->addColumn('company', 'legal_terms', 'clob', '', array(
             ));
        $this->removeColumn('company', 'invoice_legal_terms');
        $this->removeColumn('company', 'estimate_legal_terms');
    }
}