<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('sf_guard_user_profile', 'min_stock_level', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('sf_guard_user_profile', 'min_stock_level');
    }
}