<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('product', 'stock', 'integer', '8', array(
             ));
        $this->addColumn('product', 'min_stock_level', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('product', 'stock');
        $this->removeColumn('product', 'min_stock_level');
    }
}