<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version28 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('supplier', 'supplier_payment_type_id_payment_type_id', array(
             'name' => 'supplier_payment_type_id_payment_type_id',
             'local' => 'payment_type_id',
             'foreign' => 'id',
             'foreignTable' => 'payment_type',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('supplier', 'supplier_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('supplier', 'supplier_payment_type_id_payment_type_id');
        $this->removeIndex('supplier', 'supplier_payment_type_id', array(
             'fields' => 
             array(
              0 => 'payment_type_id',
             ),
             ));
    }
}