<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version31 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('customer', 'tax_condition');
        $this->removeColumn('supplier', 'tax_condition');
        $this->addColumn('customer', 'tax_condition_id', 'integer', '8', array(
             ));
        $this->addColumn('supplier', 'tax_condition_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('customer', 'tax_condition', 'string', '10', array(
             ));
        $this->addColumn('supplier', 'tax_condition', 'string', '10', array(
             ));
        $this->removeColumn('customer', 'tax_condition_id');
        $this->removeColumn('supplier', 'tax_condition_id');
    }
}