<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version30 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('tax_condition', 'tax_condition_company_id_company_id', array(
             'name' => 'tax_condition_company_id_company_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'company',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('tax_condition', 'tax_condition_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('tax_condition', 'tax_condition_company_id_company_id');
        $this->removeIndex('tax_condition', 'tax_condition_company_id', array(
             'fields' => 
             array(
              0 => 'company_id',
             ),
             ));
    }
}