<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common', 'supplier_comments', 'clob', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common', 'supplier_comments');
    }
}